services:

  runner:
    image: docker.io/gitea/runner:3
    container_name: gitea_act_runner
    restart: unless-stopped

    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "${GITEA_INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${RUNNER_TOKEN}"
      GITEA_RUNNER_NAME: "home-server-runner"

    ports:
      - "8088:8088"

    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - gitea_gitea

networks:
  gitea_gitea:
    external: true